# This is a basic workflow to help you get started with Actions

name: Refresh

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3am

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #   - name: Trigger Auto-Regen
    #     run: |
    #       curl --fail --request POST \
    #         --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
    #         --header "Authorization: Bearer $AUTO_REGEN_TOKEN"
    #     env:
    #       # Token with repo access as GitHub does
    #       USER_TOKEN: ${{ secrets.AUTO_REGEN_TOKEN }}
